apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - args:
            - --leader-elect
            - --leader-election-id=routernetes-operator
          image: controller:latest
          name: manager
          env:
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: RELATED_IMAGE_ROUTERNETES
              value: quay.io/routernetes/routernetes@sha256:dd5894c23377173fe9b1c0a1040d141d9c24bc708759b4c08b8b6c62706298fe
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 10m
              memory: 256Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
