apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "routernetes.github.io/v1alpha1",
          "kind": "Router",
          "metadata": {
            "name": "router-sample"
          },
          "spec": {
            "dhcp": {
              "dnsServer": "10.0.0.1",
              "domain": "network.lan",
              "endIP": "10.0.0.150",
              "gateway": "10.0.0.1",
              "leaseTime": "12h",
              "mask": "255.255.255.0",
              "startIP": "10.0.0.50"
            },
            "dns": {
              "upstreamServers": [
                "8.8.8.8",
                "8.8.4.4"
              ]
            },
            "firewall": {
              "outside": {
                "services": [
                  "ssh"
                ]
              }
            },
            "interfaces": {
              "inside": [
                {
                  "ipv4": {
                    "address": "10.0.0.1/24",
                    "method": "manual"
                  },
                  "name": "enp0s20u1"
                }
              ],
              "outside": [
                {
                  "ipv4": {
                    "method": "auto"
                  },
                  "name": "eno1"
                }
              ]
            },
            "updates": {
              "day": "Sun",
              "enabled": true,
              "time": "04:00",
              "timezone": "UTC"
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.21.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: routernetes-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Router
      name: routers.routernetes.github.io
      version: v1alpha1
  description: Home Router Operator
  displayName: Routernetes
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - persistentvolumeclaims
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - routernetes.github.io
          resources:
          - routers
          - routers/status
          - routers/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: routernetes-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: routernetes-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:6789
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=routernetes-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/routernetes/routernetes-operator:0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 768Mi
                  requests:
                    cpu: 10m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: routernetes-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: routernetes-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - router
  links:
  - name: Routernetes Operator
    url: https://routernetes-operator.domain
  maturity: alpha
  provider:
    name: Routernetes
    url: routernetes.github.io
  version: 0.0.1
