# permissions for end users to view routers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: router-viewer-role
rules:
  - apiGroups:
      - routernetes.net
    resources:
      - routers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - routernetes.net
    resources:
      - routers/status
    verbs:
      - get
