apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[]"
    capabilities: Full Lifecycle
  name: routernetes-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: A Router defines the configuration for an all-in-one home router
        displayName: Router
        kind: Router
        name: routers.routernetes.net
        version: v1alpha1
  description: Routernetes uses the Kubernetes API to create a customizable and auto-updating home router
  displayName: Routernetes
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - router
  links:
    - name: Routernetes
      url: https://routernetes.net
  maturity: alpha
  minKubeVersion: 1.21.0
  provider:
    name: Routernetes
    url: routernetes.net
  version: 0.0.0
