apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[]"
    capabilities: Full Lifecycle
    categories: Networking
    containerImage: quay.io/routernetes/routernetes-operator
    repository: https://github.com/routernetes/routernetes-operator
  name: routernetes-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: A Router defines the configuration for an all-in-one home router
        displayName: Router
        kind: Router
        name: routers.routernetes.net
        version: v1alpha1
  description: |
    Routernetes uses the Kubernetes API to create a customizable and auto-updating home router
    ## INSTALLATION
    Please note that this operator is designed to be used on a specifically configured single-node Kubernetes cluster.

    **Please visit [https://routernetes.net](https://routernetes.net) for installation instructions**
  displayName: Routernetes
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - router
  links:
    - name: Routernetes
      url: https://routernetes.net
  maintainers:
    - email: logan@bacoosta.com
      name: Logan McNaughton
  maturity: alpha
  minKubeVersion: 1.21.0
  provider:
    name: Routernetes
    url: routernetes.net
  version: 0.0.0
