apiVersion: routernetes.net/v1alpha1
kind: Router
metadata:
  name: router-sample
  namespace: routernetes
spec:
  dhcp:
    startIP: "192.168.64.50"
    endIP: "192.168.64.150"
    mask: "255.255.255.0"
    leaseTime: 12h
    gateway: "192.168.64.1"
    dnsServer: "192.168.64.1"
    domain: network.lan
  dns:
    listenInterface: br0
    upstreamServers:
      - "8.8.8.8"
      - "8.8.4.4"
  firewall:
    outside:
      services:
        - ssh
  interfaces:
    outside:
      - name: eno1
        type: ethernet
        ipv4:
          method: auto
    inside:
      - name: br0
        type: bridge
        members:
          - enp0s20u1
        ipv4:
          method: manual
          address: 192.168.64.1/24
  osUpdates:
    enabled: true
    timezone: UTC
    day: Sun
    time: "04:00"
