apiVersion: routernetes.net/v1alpha1
kind: Router
metadata:
  name: my-router
  namespace: routernetes
spec:
  dhcp:
    startIP: "192.168.64.50"
    endIP: "192.168.64.150"
    mask: "255.255.255.0"
    leaseTime: 12h
    gateway: "192.168.64.1"
    dnsServer: "192.168.64.1"
    domain: network.lan
  dns:
    listenInterface: enp0s20u1
    upstreamServers:
      - "8.8.8.8"
      - "8.8.4.4"
  firewall:
    outside:
      services: []
  interfaces:
    - name: eno1
      type: ethernet
      zone: outside
      ipv4:
        method: auto
    - name: enp0s20u1
      type: ethernet
      ipv4:
        method: manual
        address: 192.168.64.1/24
  osUpdates:
    enabled: true
    timezone: "America/New_York"
    day: Sun
    time: "04:00"
