---
- name: restart daemonset
  kubernetes.core.k8s:
    api_version: v1
    kind: Pod
    namespace: "{{ ansible_operator_meta.namespace }}"
    label_selectors:
      - "app=r9s"
    state: absent
  when: not daemonset_status.changed
