---
dhcp:
  startIP: "192.168.64.50"
  endIP: "192.168.64.150"
  mask: "255.255.255.0"
  leaseTime: 12h
  gateway: "192.168.64.1"
  dnsServer: "192.168.64.1"
  domain: network.lan
dns:
  upstreamServers:
    - "8.8.8.8"
    - "8.8.4.4"
firewall:
  outside:
    services: []
osUpdates:
  enabled: true
  timezone: UTC
  day: Sun
  time: "04:00"
