---
- name: dnsmasq-config
  kubernetes.core.k8s:
    template: dnsmasq-config.yaml.j2
- name: firewalld-config
  kubernetes.core.k8s:
    template: firewalld-config.yaml.j2
- name: zincati-config
  kubernetes.core.k8s:
    template: zincati-config.yaml.j2
- name: dhcp-pvc
  kubernetes.core.k8s:
    template: dhcp-pvc.yaml.j2
- name: daemonset
  kubernetes.core.k8s:
    template: daemonset.j2
