# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
  - bases/routernetes-operator.clusterserviceversion.yaml
  - ../default
  - ../samples
  - ../scorecard

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: ClusterServiceVersion
      name: routernetes-operator\.v.*
    path: patches/icon.yaml
