name: Publish operator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Use podman
        run: |
          which docker
          which podman

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build operator
        run: |
          make docker-build docker-push

      - name: Build operator bundle
        run: |
          make bundle bundle-build bundle-push
