name: Publish operator

on:
  release:
    types: [published]
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set release version
        if: ${{ github.event_name == 'release' }}
        run: |
          tag=${{ github.ref_name }}
          echo "VERSION=${tag:1}" >> $GITHUB_ENV

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: install operator-sdk
        run: |
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
          export OS=$(uname | awk '{print tolower($0)}')
          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.22.0
          curl -L -o /usr/local/bin/operator-sdk ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
          chmod +x /usr/local/bin/operator-sdk

      - name: Build operator
        run: |
          make podman-build podman-push

      - name: Build operator bundle
        run: |
          make bundle bundle-build

      - name: Validate bundle
        run: |
          operator-sdk bundle validate ./bundle --select-optional suite=operatorframework

      - name: push bundle
        run: |
          make bundle-push

      - name: Build operator catalog
        run: |
          make catalog-build

      - name: Save bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: bundle/
